### ISSUE TITLE
是否可以增加arm的安装包。。

### ISSUE THREAD

**Issue by xztxy** [MvsCode/frps-onekey#10]
树莓派安装了linux 64位的系统，一直启动不了，后来才发现。。自动下载的不匹配。。能否适配下~~

**Comment by MvsCode** [comment]
> 树莓派安装了linux 64位的系统，一直启动不了，后来才发现。。自动下载的不匹配。。能否适配下~~
frp版本没有你支持的系统？

**Comment by xztxy** [comment]
> > 树莓派安装了linux 64位的系统，一直启动不了，后来才发现。。自动下载的不匹配。。能否适配下~~
> > frp版本没有你支持的系统？

有，我自己替换了frp安装包可以用，只是说脚本一键安装的版本不匹配~

**Comment by MvsCode** [comment]
> > > 树莓派安装了linux 64位的系统，一直启动不了，后来才发现。。自动下载的不匹配。。能否适配下~~
> > > frp版本没有你支持的系统？
> 
> 有，我自己替换了frp安装包可以用，只是说脚本一键安装的版本不匹配~

你的系统要求是什么版本，我看看

**Comment by xztxy** [comment]
> > > > 树莓派安装了linux 64位的系统，一直启动不了，后来才发现。。自动下载的不匹配。。能否适配下~~
> > > > frp版本没有你支持的系统？
> > 
> > 
> > 有，我自己替换了frp安装包可以用，只是说脚本一键安装的版本不匹配~
> 
> 你的系统要求是什么版本，我看看

arm架构的树莓派，安装的ubuntu64位系统。。

**Comment by MvsCode** [comment]
> > > > > 树莓派安装了linux 64位的系统，一直启动不了，后来才发现。。自动下载的不匹配。。能否适配下~~
> > > > > frp版本没有你支持的系统？
> > > 
> > > 
> > > 有，我自己替换了frp安装包可以用，只是说脚本一键安装的版本不匹配~
> > 
> > 你的系统要求是什么版本，我看看
> 
> arm架构的树莓派，安装的ubuntu64位系统。。

脚本是支持ubuntu14-16的32/64位的，你安装失败显示什么

**Comment by xztxy** [comment]
> > > > > > 树莓派安装了linux 64位的系统，一直启动不了，后来才发现。。自动下载的不匹配。。能否适配下~~
> > > > > > frp版本没有你支持的系统？
> > > > 
> > > > 
> > > > 有，我自己替换了frp安装包可以用，只是说脚本一键安装的版本不匹配~
> > > 
> > > 
> > > 你的系统要求是什么版本，我看看
> > 
> > 
> > arm架构的树莓派，安装的ubuntu64位系统。。
> 
> 脚本是支持ubuntu14-16的32/64位的，你安装失败显示什么

是支持，也安装成功了，启动一直失败,后来自己是替换了arm的64位版本就可以启动了~~

**Comment by MvsCode** [comment]
> > > > > > > 树莓派安装了linux 64位的系统，一直启动不了，后来才发现。。自动下载的不匹配。。能否适配下~~
> > > > > > > frp版本没有你支持的系统？
> > > > > 
> > > > > 
> > > > > 有，我自己替换了frp安装包可以用，只是说脚本一键安装的版本不匹配~
> > > > 
> > > > 
> > > > 你的系统要求是什么版本，我看看
> > > 
> > > 
> > > arm架构的树莓派，安装的ubuntu64位系统。。
> > 
> > 脚本是支持ubuntu14-16的32/64位的，你安装失败显示什么
> 
> 是支持，也安装成功了，启动一直失败,后来自己是替换了arm的64位版本就可以启动了~~

明白，你理一理，既然安装成功也就是说脚本在系统可以运行，是支持的，那有可能是脚本识别你的系统下载错了版本，启动不成功，提示什么呢

**Comment by xztxy** [comment]
> > > > > > > > 树莓派安装了linux 64位的系统，一直启动不了，后来才发现。。自动下载的不匹配。。能否适配下~~
> > > > > > > > frp版本没有你支持的系统？
> > > > > > 
> > > > > > 
> > > > > > 有，我自己替换了frp安装包可以用，只是说脚本一键安装的版本不匹配~
> > > > > 
> > > > > 
> > > > > 你的系统要求是什么版本，我看看
> > > > 
> > > > 
> > > > arm架构的树莓派，安装的ubuntu64位系统。。
> > > 
> > > 
> > > 脚本是支持ubuntu14-16的32/64位的，你安装失败显示什么
> > 
> > 
> > 是支持，也安装成功了，启动一直失败,后来自己是替换了arm的64位版本就可以启动了~~
> 
> 明白，你理一理，既然安装成功也就是说脚本在系统可以运行，是支持的，那有可能是脚本识别你的系统下载错了版本，启动不成功，提示什么呢

之前的报错我没怎么留意。和你自己手动安装，放进去一个不匹配的版本运行不了是一个道理。我现在这个树莓派3b+专门用作frp服务器已经正在使用中,不太方便测试再看。其实现在也没事，主要当时发现问题，和您反馈下~感谢~！

**Comment by MvsCode** [comment]
> > > > > > > > > 树莓派安装了linux 64位的系统，一直启动不了，后来才发现。。自动下载的不匹配。。能否适配下~~
> > > > > > > > > frp版本没有你支持的系统？
> > > > > > > 
> > > > > > > 
> > > > > > > 有，我自己替换了frp安装包可以用，只是说脚本一键安装的版本不匹配~
> > > > > > 
> > > > > > 
> > > > > > 你的系统要求是什么版本，我看看
> > > > > 
> > > > > 
> > > > > arm架构的树莓派，安装的ubuntu64位系统。。
> > > > 
> > > > 
> > > > 脚本是支持ubuntu14-16的32/64位的，你安装失败显示什么
> > > 
> > > 
> > > 是支持，也安装成功了，启动一直失败,后来自己是替换了arm的64位版本就可以启动了~~
> > 
> > 明白，你理一理，既然安装成功也就是说脚本在系统可以运行，是支持的，那有可能是脚本识别你的系统下载错了版本，启动不成功，提示什么呢
> 
> 之前的报错我没怎么留意。和你自己手动安装，放进去一个不匹配的版本运行不了是一个道理。我现在这个树莓派3b+专门用作frp服务器已经正在使用中,不太方便测试再看。其实现在也没事，主要当时发现问题，和您反馈下~感谢~！

嗯嗯，主要我手上也没arm的机器，测试也不好测试，你可以fork过去，把优选amd改成arm

**Comment by eric8390** [comment]
能写一个arm的出来吗，我不会替换arm版本

**Comment by gubindp** [comment]
> 

的确遇到了这个问题。一开始的用着这个一键脚本，跟着up主 一直enter ，最后也告诉我安装结束了。立马去搞那个域名。搞了半天 那个不能进去，在仔细看看 报错那个 frp 显示版本号的那个文件29行“版本错误”。后来又装了两三遍，发现中间有一步骤直接 安装的是x86架构文件。 

请问如何替换呢？是自己下载下来上传么？

**Comment by gubindp** [comment]
> 自己

请问 这个 怎么手动替换呢？刚刚接触，不是很明白。感谢。

**Comment by gubindp** [comment]
> 

晚上回去，我去贴一下那个报错代码
