### ISSUE TITLE
能否自定义版本，路由器上的版本只有2.7，服务器用2.8启动不了

### ISSUE THREAD

**Issue by lukemin** [MvsCode/frps-onekey#11]
能否自定义版本，路由器上的版本只有2.7，服务器用2.8启动不了

**Comment by MvsCode** [comment]
> 能否自定义版本，路由器上的版本只有2.7，服务器用2.8启动不了

你试试用我放在阿里云的脚本，那个我还没更新到v0.28.0

**Comment by lukemin** [comment]
好的，谢谢。

**Comment by wlwuliao** [comment]
您好，能提供一个0.24.1的脚本吗，或者告诉我如何在您的脚本上替换，新版本和客户端不兼容，自己手动搭建没有成功，谢谢
