### ISSUE TITLE
选择的gitee，到最后一步直接报错

### ISSUE THREAD

**Issue by zhang7249** [mvscode/frps-onekey#113]
transport protocol support: enable

============== Check your input ==============
You Server IP      : 
Bind port          : 5443
vhost http port    : 80
vhost https port   : 443
Dashboard port     : 6443
Dashboard user     : admin
Dashboard password : ZDDOhcB4
token              : ArWhkhHcFI744bHd
subdomain_host     : 
tcp mux            : true
Max Pool count     : 5
Log level          : info
Log max days       : 3
Log file           : enable
transport protocol : enable
kcp bind port      : 5443
quic bind port     : 443
==============================================

Press any key to start...or Press Ctrl+c to cancel
frps install path:/usr/local/frps
config file for frps ... done
download frps ... failed

**Comment by mvscode** [comment]
最新版本frp v0.59.0 文件包还没上传到gitee，你可以在gitee push 试试

**Comment by mvscode** [comment]
> 最新版本frp v0.59.0 文件包还没上传到gitee，你可以在gitee push 试试

Done
