### ISSUE TITLE
问下客户端的安装脚本在哪里

### ISSUE THREAD

**Issue by KlausMikealsonK** [MvsCode/frps-onekey#12]
我服务端已安装到了公网的服务器上了，在你的readme上没有看到内网客户端的安装脚本说明。刚接触frp，麻烦回复下

**Comment by MvsCode** [comment]
请问你的客户端设备是什么
主要分为：电脑端，路由器，盒子，Linux

**Comment by KlausMikealsonK** [comment]
我客户端设备 有个乌班图的系统，还有个linux路由器的开发板
