### ISSUE TITLE
关闭log后会导致/dev/null无法访问

### ISSUE THREAD

**Issue by xinnanlyu** [MvsCode/frps-onekey#17]
在安装过程中，如果将log_file功能选择为disable，会导致系统/dev/null: Permission Denied，即便使用chmod 600 /dev/null修复后，也会间歇性导致/dev/null: Permission Denied，以至于很多系统服务无法正常工作。

**Comment by MvsCode** [comment]
> 在安装过程中，如果将log_file功能选择为disable，会导致系统/dev/null: Permission Denied，即便使用chmod 600 /dev/null修复后，也会间歇性导致/dev/null: Permission Denied，以至于很多系统服务无法正常工作。

建议不要关闭日志功能，或者直接删掉试试
