### ISSUE TITLE
使用第一个脚本（Github），选择阿里云安装frp会失败。

### ISSUE THREAD

**Issue by 1424753988** [MvsCode/frps-onekey#18]
1.使用第一个脚本（Github），选择阿里云安装frp会提示下载失败。
2.使用第二个脚本（阿里云），选择阿里云安装frp不是最新版本。

**Comment by 1424753988** [comment]
使用github脚本中的github镜像安装，则没有问题，但有些国内机器会因连不上github或者下载速度极慢而导致安装失败。

**Comment by MvsCode** [comment]
> 1.使用第一个脚本（Github），选择阿里云安装frp会提示下载失败。
> 2.使用第二个脚本（阿里云），选择阿里云安装frp不是最新版本。

最近比较忙，阿里云code上的版本没更新

**Comment by MvsCode** [comment]
已更新至0.31.0
