### ISSUE TITLE
frp更新到了新版

### ISSUE THREAD

**Issue by vpsceo** [MvsCode/frps-onekey#23]
Frp最新版本：0.31.2

  ./install-frps.sh update   升级不上去  始终是0.31.0

**Comment by vpsceo** [comment]
明白怎么回事了，脚本要重新下载一次在执行升级才可以。

**Comment by MvsCode** [comment]
> 明白怎么回事了，脚本要重新下载一次在执行升级才可以。

确实有这个Bug，但是问题不大就一直没弄，你有好建议可以分享

**Comment by as1543100166** [comment]
我这里还是0.31.0无法升级..两个源都试过，甚至重装系统都是0.31.0

**Comment by MvsCode** [comment]
> ~我这里还是0.31.0无法升级，甚至重装系统都是0.31.0~
> 使用github源正常了
> @MvsCode 能不能更新一下aliyun源的版本..国内github拉取文件总是失败 aliyun上的还是0.31.0

没有更新及时，抱歉

**Comment by MvsCode** [comment]
> > ~我这里还是0.31.0无法升级，甚至重装系统都是0.31.0~
> > 使用github源正常了
> > @MvsCode 能不能更新一下aliyun源的版本..国内github拉取文件总是失败 aliyun上的还是0.31.0
> 
> 没有更新及时，抱歉

Aliyun Code has Upgard

**Comment by as1543100166** [comment]
> Aliyun Code has Upgard

感谢

**Comment by jayvee902** [comment]
发个连同frpc的一键安装命令上来吧。

**Comment by MvsCode** [comment]
> 发个连同frpc的一键安装命令上来吧。

支持frp客户端的设备种类繁多，很多支持frp固件的都有操作界面，更适合使用，除了一些机器

**Comment by bfth1f** [comment]
安装完成后，每次运行就出错了。
Starting Frps(0.32.0)...start failed

**Comment by MvsCode** [comment]
> 安装完成后，每次运行就出错了。
> Starting Frps(0.32.0)...start failed

就Start failed？建议重新安装

**Comment by bfth1f** [comment]
> > 安装完成后，每次运行就出错了。
> > Starting Frps(0.32.0)...start failed
> 
> 就Start failed？建议重新安装

重新安装了几次，还是一样 Starting Frps(0.32.0)...start failed

**Comment by ws115** [comment]
我也是Starting Frps(0.32.0)...start failed

**Comment by Steady66666** [comment]
start failed 情况我是直接运行`/usr/local/frps/frps` 看报错的，我的报错好像是7000端口？就很迷，7000貌似不需要，但是之前关闭的docker占用了这个端口，重启一下服务器就好了，`/usr/local/frps/frps`可以正常跑，运行`frps start`成功
