### ISSUE TITLE
在最后开始安装时下载出错

### ISSUE THREAD

**Issue by summerkangk** [MvsCode/frps-onekey#26]
Press any key to start...or Press Ctrl+c to cancel
frps install path:/usr/local/frps
config file for frps ... done
download frps ...
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat 'frp_0.32.0_linux_amd64/frps': No such file or directory
 failed

**Comment by MvsCode** [comment]
> Press any key to start...or Press Ctrl+c to cancel
> 
> frps install path:/usr/local/frps
> 
> config file for frps ... done
> 
> download frps ...
> 
> gzip: stdin: not in gzip format
> 
> tar: Child returned status 1
> 
> tar: Error is not recoverable: exiting now
> 
> mv: cannot stat 'frp_0.32.0_linux_amd64/frps': No such file or directory
> 
>  failed
> 
> 


原因是这个压缩包没有用gzip格式压缩，所以不用加z指令。

在解压tar.gz文件的时候报错

百度可以查到

**Comment by wongsyrone** [comment]
并不是，FRPS_INIT 打成了 FRPS.INIT，另外fun_getVer 打成了 fun_get_version

**Comment by MvsCode** [comment]
> 并不是，FRPS_INIT 打成了 FRPS.INIT，另外fun_getVer 打成了 fun_get_version

按照你的报错日志是 解压方式不一致

**Comment by wongsyrone** [comment]
你自己看 https://github.com/MvsCode/frps-onekey/blob/master/install-frps.sh#L173

首先如果直接回车，默认设置会到187行，走gitee的下载链接
另外 github_download_url 打成了 gitub_download_url， 导致github的链接不完整，根本就下不来那个文件，后面的命令肯定失败，和gzip半毛钱关系都没有

**Comment by MvsCode** [comment]
> 你自己看 https://github.com/MvsCode/frps-onekey/blob/master/install-frps.sh#L173
> 
> 首先如果直接回车，默认设置会到187行，走gitee的下载链接
> 另外 github_download_url 打成了 gitub_download_url， 导致github的链接不完整，根本就下不来那个文件，后面的命令肯定失败，和gzip半毛钱关系都没有

嗯嗯，看到了，现在再试试

**Comment by wongsyrone** [comment]
我自己修好了，另外还改了两处
```diff
@@ -821,8 +822,8 @@ update_program_server_clang(){
         checkos
         check_centosversion
         check_os_bit
-    fun_get_version
-        remote_init_version=`wget  -qO- ${FRPS.INIT} | sed -n '/'^version'/p' | cut -d\" -f2`
+    fun_getVer
+        remote_init_version=`wget  -qO- ${FRPS_INIT} | sed -n '/'^version'/p' | cut -d\" -f2`
         local_init_version=`sed -n '/'^version'/p' ${program_init} | cut -d\" -f2`
         install_shell=${strPath}
         if [ ! -z ${remote_init_version} ];then
```

**Comment by summerkangk** [comment]
我是复制粘贴的命令（也可能是谷歌自动翻译的原因没仔细看）

**Comment by wongsyrone** [comment]
我是在脚本最前加了 set -x 看出来的

**Comment by MvsCode** [comment]
> 我自己修好了，另外还改了两处
> 
> ```diff
> @@ -821,8 +822,8 @@ update_program_server_clang(){
>          checkos
>          check_centosversion
>          check_os_bit
> -    fun_get_version
> -        remote_init_version=`wget  -qO- ${FRPS.INIT} | sed -n '/'^version'/p' | cut -d\" -f2`
> +    fun_getVer
> +        remote_init_version=`wget  -qO- ${FRPS_INIT} | sed -n '/'^version'/p' | cut -d\" -f2`
>          local_init_version=`sed -n '/'^version'/p' ${program_init} | cut -d\" -f2`
>          install_shell=${strPath}
>          if [ ! -z ${remote_init_version} ];then
> ```

Thx
