### ISSUE TITLE
无法启动frps的问题

### ISSUE THREAD

**Issue by lw916** [MvsCode/frps-onekey#29]
/etc/init.d/frps: line 45: [: 10472: binary operator expected
Starting Frps(0.33.0).../etc/init.d/frps: line 45: [: 10472: binary operator expected
start failed

麻烦问下，这是什么报错

**Comment by lw916** [comment]
fun_check_run(){
    PID=`ps -ef | grep -v grep | grep -i "${BIN}" | awk '{print $2}'`
    if [ ! -z **"$PID**" ]; then
        return 0
    else
        return 1
    fi
}
这里可能要加个冒号

**Comment by MvsCode** [comment]
你直接pull code

**Comment by MvsCode** [comment]
> fun_check_run(){
> 
>     PID=`ps -ef | grep -v grep | grep -i "${BIN}" | awk '{print $2}'`
> 
>     if [ ! -z **"$PID**" ]; then
> 
>         return 0
> 
>     else
> 
>         return 1
> 
>     fi
> 
> }
> 
> 这里可能要加个冒号

你直接pull code

**Comment by lw916** [comment]
行我试试
