### ISSUE TITLE
 frp服务启动失败，请检查服务端“TCP多路复用(tcp_mux)”设置，确保与客户端完全一致！

### ISSUE THREAD

**Issue by geekbb** [MvsCode/frps-onekey#32]
确定TCP多路复用是一致的，就是启动不了

**Comment by langliang3241** [comment]
用最新的源码【 OpenWrt R23.4.1 / LuCI Master (git-23.109.50273-11b9572) 】编译出的固件 7621的京东云和歌华链 frpc 都报错：‘“frp服务启动失败，请检查服务端 “TCP多路复用(tcp_mux)”设置，确保与客户端完全一致！”，frpc 版本是：0.47.0-1 服务器端 tcp_mux 设置是true ，frps 版本也是0.47 ，以前的老版本都可以正常启动，有解决办法么
