### ISSUE TITLE
停止脚本失效,,stop后,进程还在,必须kill

### ISSUE THREAD

**Issue by huang7dede** [MvsCode/frps-onekey#33]
0.33最新版本,stop脚本不管用,,,造成无法重启,,必须kill后才能start

root@ubuntu:~#  /etc/init.d/frps stop

+---------------------------------------------------------+
|     Manager for Frps, Author Clang, Mender MvsCode      |
+---------------------------------------------------------+

Frps is not running.
root@ubuntu:~# ps -aux | grep frps
root      45423  0.0  1.1 715808 11356 pts/0    Sl   09:15   0:02 /usr/local/frps/frps -c /usr/local/frps/frps.ini
root      57188  0.0  0.1  13144  1116 pts/0    S+   12:01   0:00 grep --color=auto frps
root@ubuntu:~#

**Comment by lee29** [comment]
可否增加监控重启功能[https://diannaobos.com/post/864.html](url)

**Comment by MvsCode** [comment]
> 可否增加监控重启功能[https://diannaobos.com/post/864.html](url)

什么意思？链接进不去

**Comment by lee29** [comment]
> > 可否增加监控重启功能[https://diannaobos.com/post/864.html](url)
> 
> 什么意思？链接进不去

> 监控FRPS端口并自动重启FRPS脚本
30970FRP教程 | 2019年10月10日
linux下监控服务进程监听的端口,当服务器的监听端口停止时,自动重启服务进程。

如下监听frps服务器的7000端口,当7000端口不处于监听状态时或异常退出时,则自动重启frps进程服务,并记录当前时间保存到日志文件。

Bash
#!/bin/bash
#author: bos
#www: www.diannaobos.com
#Monitor FrpServer script
 
#check root user
if [ $(id -u) != "0" ]; then
    echo " Not the root user! Try using sudo Command ! "
    exit 1
fi
 
netstat -nl |grep -q 7000
if [ $? -ne 1 ];then exit; fi 
echo $(date +%T%n%F)" Restart Frp Services " >> frps.log
 
#restart frps
systemctl restart frps
将上面代码创建为Monitor_FrpServer.sh

另外定时执行该脚本,来维护进程服务的正常运行。

例如每1分钟自动执行一次，可以在周期计划中配置如下:

* * * * * sh /root/Monitor_FrpServer.sh

**Comment by lee29** [comment]
或者增加一个每天定时重启的脚本？

**Comment by MvsCode** [comment]
> 或者增加一个每天定时重启的脚本？

可以，没必要。定时重启在建好frps之后，加多几行代码指向frps就可以实现。
