### ISSUE TITLE
阿里云“download frps ... failed”

### ISSUE THREAD

**Issue by wwmgct** [MvsCode/frps-onekey#37]
frps install path:/usr/local/frps
config file for frps ... done
download frps ... **failed**
-------------------------------
还请更新下，谢谢！

**Comment by MvsCode** [comment]
已更新

**Comment by City-Zero** [comment]
阿里云仍存在该问题

**Comment by MvsCode** [comment]
> 阿里云仍存在该问题

已移除阿里雲下載地址，請使用github or gitee

**Comment by City-Zero** [comment]
> > 阿里云仍存在该问题
> 
> 已移除阿里雲下載地址，請使用github or gitee

这边是阿里云的主机下载时提示 "download frps ... failed"， github 、gitee 都提示这个。不过已经参照你的shell自己解压了文件和init文件，可以使用了
