### ISSUE TITLE
frps 在服务端无法启动

### ISSUE THREAD

**Issue by XuJian1252878** [MvsCode/frps-onekey#40]
Starting Frps(0.34.3)...start failed
使用一键安装脚本之后，frps start 会报上面的错误

并且看 log 日志里面没啥异常，日志如下：
2020/12/19 17:07:28 [I] [service.go:190] frps tcp listen on 0.0.0.0:5443
2020/12/19 17:07:28 [I] [service.go:199] frps kcp listen on udp 0.0.0.0:5443
2020/12/19 17:07:42 [I] [service.go:190] frps tcp listen on 0.0.0.0:5443
2020/12/19 17:07:42 [I] [service.go:199] frps kcp listen on udp 0.0.0.0:5443
2020/12/19 17:08:38 [I] [service.go:190] frps tcp listen on 0.0.0.0:5443
2020/12/19 17:08:38 [I] [service.go:199] frps kcp listen on udp 0.0.0.0:5443
2020/12/19 17:11:52 [I] [service.go:190] frps tcp listen on 0.0.0.0:5443
2020/12/19 17:11:52 [I] [service.go:199] frps kcp listen on udp 0.0.0.0:5443
2020/12/19 17:13:42 [I] [service.go:190] frps tcp listen on 0.0.0.0:5443
2020/12/19 17:13:42 [I] [service.go:199] frps kcp listen on udp 0.0.0.0:5443
2020/12/19 17:15:51 [I] [service.go:190] frps tcp listen on 0.0.0.0:5443
2020/12/19 17:15:51 [I] [service.go:199] frps kcp listen on udp 0.0.0.0:5443
2020/12/19 17:16:54 [I] [service.go:190] frps tcp listen on 0.0.0.0:5443
2020/12/19 17:16:54 [I] [service.go:199] frps kcp listen on udp 0.0.0.0:5443

**Comment by MvsCode** [comment]
> Starting Frps(0.34.3)...start failed
> 
> 使用一键安装脚本之后，frps start 会报上面的错误
> 
> 
> 
> 并且看 log 日志里面没啥异常，日志如下：
> 
> 2020/12/19 17:07:28 [I] [service.go:190] frps tcp listen on 0.0.0.0:5443
> 
> 2020/12/19 17:07:28 [I] [service.go:199] frps kcp listen on udp 0.0.0.0:5443
> 
> 2020/12/19 17:07:42 [I] [service.go:190] frps tcp listen on 0.0.0.0:5443
> 
> 2020/12/19 17:07:42 [I] [service.go:199] frps kcp listen on udp 0.0.0.0:5443
> 
> 2020/12/19 17:08:38 [I] [service.go:190] frps tcp listen on 0.0.0.0:5443
> 
> 2020/12/19 17:08:38 [I] [service.go:199] frps kcp listen on udp 0.0.0.0:5443
> 
> 2020/12/19 17:11:52 [I] [service.go:190] frps tcp listen on 0.0.0.0:5443
> 
> 2020/12/19 17:11:52 [I] [service.go:199] frps kcp listen on udp 0.0.0.0:5443
> 
> 2020/12/19 17:13:42 [I] [service.go:190] frps tcp listen on 0.0.0.0:5443
> 
> 2020/12/19 17:13:42 [I] [service.go:199] frps kcp listen on udp 0.0.0.0:5443
> 
> 2020/12/19 17:15:51 [I] [service.go:190] frps tcp listen on 0.0.0.0:5443
> 
> 2020/12/19 17:15:51 [I] [service.go:199] frps kcp listen on udp 0.0.0.0:5443
> 
> 2020/12/19 17:16:54 [I] [service.go:190] frps tcp listen on 0.0.0.0:5443
> 
> 2020/12/19 17:16:54 [I] [service.go:199] frps kcp listen on udp 0.0.0.0:5443

防火墙端口没打开

**Comment by XuJian1252878** [comment]
是把 5443 端口打开？

**Comment by MvsCode** [comment]
> 是把 5443 端口打开？

打开相对应你要使用的

**Comment by MvsCode** [comment]
> 是把 5443 端口打开？

而且你的服务器ip没有成功添加
