### ISSUE TITLE
Openwrt Frpc无法连接25端口

### ISSUE THREAD

**Issue by buildiffuse** [MvsCode/frps-onekey#42]
服务器端防火墙已开启，其余端口例如993/tcp 995/tcp 等均可开启，就是25端口不行

日志如下
2021/03/18 21:33:25 [I] [service.go:288] [b11cc3ffc962de84] login to server success, get run id [b11cc3ffc962de84], server udp port [0]
2021/03/18 21:33:25 [I] [proxy_manager.go:144] [b11cc3ffc962de84] proxy added: [DSM SMTP Buildiffuse-443 www-443 Mail-443 DSM-443 Mail Buildiffuse www]
2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [DSM] start proxy success
2021/03/18 21:33:25 [W] [control.go:178] [b11cc3ffc962de84] [SMTP] start error: port unavailable
2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Buildiffuse-443] start proxy success
2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [www-443] start proxy success
2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Mail-443] start proxy success
2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [DSM-443] start proxy success
2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Mail] start proxy success
2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Buildiffuse] start proxy success
2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [www] start proxy success
2021/03/18 21:33:59 [W] [control.go:178] [b11cc3ffc962de84] [SMTP] start error: port unavailable

**Comment by MvsCode** [comment]
> 服务器端防火墙已开启，其余端口例如993/tcp 995/tcp 等均可开启，就是25端口不行
> 
> 
> 
> 日志如下
> 
> 2021/03/18 21:33:25 [I] [service.go:288] [b11cc3ffc962de84] login to server success, get run id [b11cc3ffc962de84], server udp port [0]
> 
> 2021/03/18 21:33:25 [I] [proxy_manager.go:144] [b11cc3ffc962de84] proxy added: [DSM SMTP Buildiffuse-443 www-443 Mail-443 DSM-443 Mail Buildiffuse www]
> 
> 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [DSM] start proxy success
> 
> 2021/03/18 21:33:25 [W] [control.go:178] [b11cc3ffc962de84] [SMTP] start error: port unavailable
> 
> 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Buildiffuse-443] start proxy success
> 
> 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [www-443] start proxy success
> 
> 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Mail-443] start proxy success
> 
> 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [DSM-443] start proxy success
> 
> 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Mail] start proxy success
> 
> 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Buildiffuse] start proxy success
> 
> 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [www] start proxy success
> 
> 2021/03/18 21:33:59 [W] [control.go:178] [b11cc3ffc962de84] [SMTP] start error: port unavailable
> 
> 

80端口可以用吗

**Comment by buildiffuse** [comment]
> > 服务器端防火墙已开启，其余端口例如993/tcp 995/tcp 等均可开启，就是25端口不行
> > 日志如下
> > 2021/03/18 21:33:25 [I] [service.go:288] [b11cc3ffc962de84] login to server success, get run id [b11cc3ffc962de84], server udp port [0]
> > 2021/03/18 21:33:25 [I] [proxy_manager.go:144] [b11cc3ffc962de84] proxy added: [DSM SMTP Buildiffuse-443 www-443 Mail-443 DSM-443 Mail Buildiffuse www]
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [DSM] start proxy success
> > 2021/03/18 21:33:25 [W] [control.go:178] [b11cc3ffc962de84] [SMTP] start error: port unavailable
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Buildiffuse-443] start proxy success
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [www-443] start proxy success
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Mail-443] start proxy success
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [DSM-443] start proxy success
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Mail] start proxy success
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Buildiffuse] start proxy success
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [www] start proxy success
> > 2021/03/18 21:33:59 [W] [control.go:178] [b11cc3ffc962de84] [SMTP] start error: port unavailable
> 
> 80端口可以用吗

测试过了，80 443 端口都没问题，就是25端口不行，问过kamatera的客服，vps没有封25端口的，会不会是被墙了？

**Comment by buildiffuse** [comment]
> > 服务器端防火墙已开启，其余端口例如993/tcp 995/tcp 等均可开启，就是25端口不行
> > 日志如下
> > 2021/03/18 21:33:25 [I] [service.go:288] [b11cc3ffc962de84] login to server success, get run id [b11cc3ffc962de84], server udp port [0]
> > 2021/03/18 21:33:25 [I] [proxy_manager.go:144] [b11cc3ffc962de84] proxy added: [DSM SMTP Buildiffuse-443 www-443 Mail-443 DSM-443 Mail Buildiffuse www]
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [DSM] start proxy success
> > 2021/03/18 21:33:25 [W] [control.go:178] [b11cc3ffc962de84] [SMTP] start error: port unavailable
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Buildiffuse-443] start proxy success
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [www-443] start proxy success
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Mail-443] start proxy success
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [DSM-443] start proxy success
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Mail] start proxy success
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Buildiffuse] start proxy success
> > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [www] start proxy success
> > 2021/03/18 21:33:59 [W] [control.go:178] [b11cc3ffc962de84] [SMTP] start error: port unavailable
> 
> 80端口可以用吗

刚刚试了下，单独设置为tcp协议 80 443都不行

**Comment by MvsCode** [comment]
> > > 服务器端防火墙已开启，其余端口例如993/tcp 995/tcp 等均可开启，就是25端口不行
> 
> > > 日志如下
> 
> > > 2021/03/18 21:33:25 [I] [service.go:288] [b11cc3ffc962de84] login to server success, get run id [b11cc3ffc962de84], server udp port [0]
> 
> > > 2021/03/18 21:33:25 [I] [proxy_manager.go:144] [b11cc3ffc962de84] proxy added: [DSM SMTP Buildiffuse-443 www-443 Mail-443 DSM-443 Mail Buildiffuse www]
> 
> > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [DSM] start proxy success
> 
> > > 2021/03/18 21:33:25 [W] [control.go:178] [b11cc3ffc962de84] [SMTP] start error: port unavailable
> 
> > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Buildiffuse-443] start proxy success
> 
> > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [www-443] start proxy success
> 
> > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Mail-443] start proxy success
> 
> > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [DSM-443] start proxy success
> 
> > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Mail] start proxy success
> 
> > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Buildiffuse] start proxy success
> 
> > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [www] start proxy success
> 
> > > 2021/03/18 21:33:59 [W] [control.go:178] [b11cc3ffc962de84] [SMTP] start error: port unavailable
> 
> > 
> 
> > 80端口可以用吗
> 
> 
> 
> 刚刚试了下，单独设置为tcp协议 80 443都不行

😂那不是被封了节奏吗

**Comment by buildiffuse** [comment]
> > > > 服务器端防火墙已开启，其余端口例如993/tcp 995/tcp 等均可开启，就是25端口不行
> > 
> > 
> > > > 日志如下
> > 
> > 
> > > > 2021/03/18 21:33:25 [I] [service.go:288] [b11cc3ffc962de84] login to server success, get run id [b11cc3ffc962de84], server udp port [0]
> > 
> > 
> > > > 2021/03/18 21:33:25 [I] [proxy_manager.go:144] [b11cc3ffc962de84] proxy added: [DSM SMTP Buildiffuse-443 www-443 Mail-443 DSM-443 Mail Buildiffuse www]
> > 
> > 
> > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [DSM] start proxy success
> > 
> > 
> > > > 2021/03/18 21:33:25 [W] [control.go:178] [b11cc3ffc962de84] [SMTP] start error: port unavailable
> > 
> > 
> > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Buildiffuse-443] start proxy success
> > 
> > 
> > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [www-443] start proxy success
> > 
> > 
> > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Mail-443] start proxy success
> > 
> > 
> > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [DSM-443] start proxy success
> > 
> > 
> > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Mail] start proxy success
> > 
> > 
> > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Buildiffuse] start proxy success
> > 
> > 
> > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [www] start proxy success
> > 
> > 
> > > > 2021/03/18 21:33:59 [W] [control.go:178] [b11cc3ffc962de84] [SMTP] start error: port unavailable
> > 
> > 
> > > 
> > 
> > 
> > > 80端口可以用吗
> > 
> > 
> > 刚刚试了下，单独设置为tcp协议 80 443都不行
> 
> 😂那不是被封了节奏吗

哎这，，，，小白不太懂，那为啥http和https又可以转发呢，不行那只能换vps了

**Comment by MvsCode** [comment]
> > > > > 服务器端防火墙已开启，其余端口例如993/tcp 995/tcp 等均可开启，就是25端口不行
> 
> > > 
> 
> > > 
> 
> > > > > 日志如下
> 
> > > 
> 
> > > 
> 
> > > > > 2021/03/18 21:33:25 [I] [service.go:288] [b11cc3ffc962de84] login to server success, get run id [b11cc3ffc962de84], server udp port [0]
> 
> > > 
> 
> > > 
> 
> > > > > 2021/03/18 21:33:25 [I] [proxy_manager.go:144] [b11cc3ffc962de84] proxy added: [DSM SMTP Buildiffuse-443 www-443 Mail-443 DSM-443 Mail Buildiffuse www]
> 
> > > 
> 
> > > 
> 
> > > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [DSM] start proxy success
> 
> > > 
> 
> > > 
> 
> > > > > 2021/03/18 21:33:25 [W] [control.go:178] [b11cc3ffc962de84] [SMTP] start error: port unavailable
> 
> > > 
> 
> > > 
> 
> > > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Buildiffuse-443] start proxy success
> 
> > > 
> 
> > > 
> 
> > > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [www-443] start proxy success
> 
> > > 
> 
> > > 
> 
> > > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Mail-443] start proxy success
> 
> > > 
> 
> > > 
> 
> > > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [DSM-443] start proxy success
> 
> > > 
> 
> > > 
> 
> > > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Mail] start proxy success
> 
> > > 
> 
> > > 
> 
> > > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [Buildiffuse] start proxy success
> 
> > > 
> 
> > > 
> 
> > > > > 2021/03/18 21:33:25 [I] [control.go:180] [b11cc3ffc962de84] [www] start proxy success
> 
> > > 
> 
> > > 
> 
> > > > > 2021/03/18 21:33:59 [W] [control.go:178] [b11cc3ffc962de84] [SMTP] start error: port unavailable
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 80端口可以用吗
> 
> > > 
> 
> > > 
> 
> > > 刚刚试了下，单独设置为tcp协议 80 443都不行
> 
> > 
> 
> > 😂那不是被封了节奏吗
> 
> 
> 
> 哎这，，，，小白不太懂，那为啥http和https又可以转发呢，不行那只能换vps了

http跟https不够用吗，如果不够用你就知道为啥封，一般是运营商封，用其他方法试试，不着急换vps

**Comment by buildiffuse** [comment]
好的谢谢~~用dns域名解析搞定了~
