### ISSUE TITLE
无法更新到v0.36.2 [2021/03/22]

### ISSUE THREAD

**Issue by chouniu666** [MvsCode/frps-onekey#44]
Please select frps download url:
[1].aliyun (default)
[2].github 
Enter your choice (1, 2 or exit. default [aliyun]): 2
-----------------------------------
       Your select: 2    
-----------------------------------
frps  local version 0.36.1
frps remote version 0.36.1
no need to update !!!

**Comment by MvsCode** [comment]
> Please select frps download url:
> 
> [1].aliyun (default)
> 
> [2].github 
> 
> Enter your choice (1, 2 or exit. default [aliyun]): 2
> 
> -----------------------------------
> 
>        Your select: 2    
> 
> -----------------------------------
> 
> frps  local version 0.36.1
> 
> frps remote version 0.36.1
> 
> no need to update !!!

试试阿里云

**Comment by chouniu666** [comment]
试过了，还那样，我卸载了，重新安装了最新版
