### ISSUE TITLE
Starting Frps(0.37.0)...start failed

### ISSUE THREAD

**Issue by JarvisPongSky** [MvsCode/frps-onekey#45]
# 问题描述

安装完后启动 frps 失败，日志没看到相关报错信息

## Operating System

Tencent Cloud 2核4G

CentOS Linux release 8.2.2004 (Core)

## frps.log

``` log
2021/06/14 19:46:08 [I] [root.go:200] frps uses config file: /usr/local/frps/frps.ini
2021/06/14 19:46:08 [I] [service.go:192] frps tcp listen on 0.0.0.0:5443
2021/06/14 19:46:08 [I] [service.go:202] frps kcp listen on udp 0.0.0.0:5443
```

## frps.ini

dashboard_user、dashboard_pwd、token 在 issues 被我替换成 XXXXXX

subdomain_host 在 issues 被我替换成 domain.com

``` txt
# [common] is integral section
[common]
# A literal address or host name for IPv6 must be enclosed
# in square brackets, as in "[::1]:80", "[ipv6-host]:http" or "[ipv6-host%zone]:80"
bind_addr = 0.0.0.0
bind_port = 5443
# udp port used for kcp protocol, it can be same with 'bind_port'
# if not set, kcp is disabled in frps
kcp_bind_port = 5443
# if you want to configure or reload frps by dashboard, dashboard_port must be set
dashboard_port = 6443
# dashboard assets directory(only for debug mode)
dashboard_user = XXXXXX
dashboard_pwd = XXXXXX
# assets_dir = ./static
vhost_http_port = 80
vhost_https_port = 443
# console or real logFile path like ./frps.log
log_file = ./frps.log
# debug, info, warn, error
log_level = debug
log_max_days = 3
# auth token
token = XXX
# It is convenient to use subdomain configure for http、https type when many people use one frps server together.
subdomain_host = domain.com
# only allow frpc to bind ports you list, if you set nothing, there won't be any limit
#allow_ports = 1-65535
# pool_count in each proxy will change to max_pool_count if they exceed the maximum value
max_pool_count = 50
# if tcp stream multiplexing is used, default is true
tcp_mux = true
```

**Comment by JarvisPongSky** [comment]
尝试排查系统版本问题，重装为 CentOS Linux release 7.9.2009 (Core) ，报错信息还是一样。

并且 log 监听的端口号 5443 没有被其他程序占用。

**Comment by MvsCode** [comment]
> 尝试排查系统版本问题，重装为 CentOS Linux release 7.9.2009 (Core) ，报错信息还是一样。
> 
> 并且 log 监听的端口号 5443 没有被其他程序占用。

看日志，脚本没有读取到机器的真实ip

**Comment by JarvisPongSky** [comment]
> > 尝试排查系统版本问题，重装为 CentOS Linux release 7.9.2009 (Core) ，报错信息还是一样。
> > 并且 log 监听的端口号 5443 没有被其他程序占用。
> 
> 看日志，脚本没有读取到机器的真实ip

机器的真实IP就是 1.15.6.103。我排查了防火墙，也是未运行状态，腾讯云的安全组 入网出网协议、端口全开放。

**Comment by JarvisPongSky** [comment]
> > 尝试排查系统版本问题，重装为 CentOS Linux release 7.9.2009 (Core) ，报错信息还是一样。
> > 并且 log 监听的端口号 5443 没有被其他程序占用。
> 
> 看日志，脚本没有读取到机器的真实ip

![image](https://user-images.githubusercontent.com/53456132/121898881-72182a80-cd56-11eb-9f7d-84fc67aad772.png)

![image](https://user-images.githubusercontent.com/53456132/121899077-a855aa00-cd56-11eb-9720-3b73567d032b.png)

机器 IP 是有正确读取到。我也排查了我误操作输出错误的内容，所以我重新安装一遍按照默认配置一路回车键 enter，启动也是报一样的错。

**Comment by JarvisPongSky** [comment]
尝试一台搬瓦工美国节点服务器，系统版本（CentOS Linux release 8.2.2004 (Core)）一样，也是报同样的错。

**Comment by MvsCode** [comment]
> 尝试一台搬瓦工美国节点服务器，系统版本（CentOS Linux release 8.2.2004 (Core)）一样，也是报同样的错。

报错logo是什么

**Comment by JarvisPongSky** [comment]
> > 尝试一台搬瓦工美国节点服务器，系统版本（CentOS Linux release 8.2.2004 (Core)）一样，也是报同样的错。
> 
> 报错logo是什么

frps.log 就三行 log，log level 是 deug 级别

``` txt
2021/06/14 19:46:08 [I] [root.go:200] frps uses config file: /usr/local/frps/frps.ini
2021/06/14 19:46:08 [I] [service.go:192] frps tcp listen on 0.0.0.0:5443
2021/06/14 19:46:08 [I] [service.go:202] frps kcp listen on udp 0.0.0.0:5443
```

**Comment by JarvisPongSky** [comment]
我屏幕录制操作了一遍安装流程，您可看下。[点我跳转🔗，72小时内有效](https://cowtransfer.com/s/6913c1805d694a)


在这里我也用文字描述说明下屏幕录制的操作流程：

1. 展示 CentOS 版本（CentOS Linux release 7.9.2009 (Core)）
2. 查看防火墙状态（not running）
3. 查看端口占用情况（5443、6443未被占用）
4. 根据 frps-onekey aliyun 一键安装脚本进行安装，过程中的配置全部按照默认的配置，一路回车 enter。
5. 安装完毕进行启动，报 frps failed。
6. 查阅 frps.log 日志，只有三行。

```txt
2021/06/14 19:46:08 [I] [root.go:200] frps uses config file: /usr/local/frps/frps.ini
2021/06/14 19:46:08 [I] [service.go:192] frps tcp listen on 0.0.0.0:5443
2021/06/14 19:46:08 [I] [service.go:202] frps kcp listen on udp 0.0.0.0:5443
```

**Comment by wrb2012** [comment]
可能是443被占用 但是脚本没提示

**Comment by itgoyo** [comment]
腾讯云也出现了楼上的问题

**Comment by itgoyo** [comment]
Starting Frps(0.38.0)...start failed
服务器：ubuntu_20.04

**Comment by PhDLuffy** [comment]
你的80和443端口被其他程序占用了，改为其他端口即可成功运行。

**Comment by kl79613** [comment]
> 你的80和443端口被其他程序占用了，改为其他端口即可成功运行。

vhost_http_port = 80
vhost_https_port = 443
请问这两个端口的作用是什么啊

**Comment by PhDLuffy** [comment]
> 
> 
> 
> 
> 
> 
> 
> 
> > 你的80和443端口被其他程序占用了，改为其他端口即可成功运行。
> 
> 
> 
> vhost_http_port = 80
> 
> vhost_https_port = 443
> 
> 请问这两个端口的作用是什么啊

用于http和https代理，跟子域名有关。
