### ISSUE TITLE
内网查看frps仪表盘及如何再次查看刚安装完的配置信息

### ISSUE THREAD

**Issue by slb116763814** [MvsCode/frps-onekey#47]
我想问两个问题
第一个，我在内网linux系统上配置好frps以后，我用内网IP不能查看frps的仪表盘吗？
第二个，我在服务器上配置好以后，会出现配置信息，然后我把SSH工具关闭以后，我再连接服务器，如何再次查看配置信息。
例如下的配置信息。

哪位知道的请告诉一下。谢谢。

Congratulations, frps install completed!
================================================
You Server IP      : 112.11.152.95
Bind port          : 5443
KCP support        : true
vhost http port    : 8880
vhost https port   : 8443
Dashboard port     : 7500
token              : 123456
subdomain_host     : 112.11.152.95
tcp_mux            : true
Max Pool count     : 50
Log level          : info
Log max days       : 3
Log file           : enable
================================================
frps Dashboard     : http://112.11.152.95:7500/
Dashboard user     : admin
Dashboard password : 123456
================================================

**Comment by MvsCode** [comment]
> 我想问两个问题
> 
> 第一个，我在内网linux系统上配置好frps以后，我用内网IP不能查看frps的仪表盘吗？
> 
> 第二个，我在服务器上配置好以后，会出现配置信息，然后我把SSH工具关闭以后，我再连接服务器，如何再次查看配置信息。
> 
> 例如下的配置信息。
> 
> 
> 
> 哪位知道的请告诉一下。谢谢。
> 
> 
> 
> Congratulations, frps install completed!
> 
> ================================================
> 
> You Server IP      : 112.11.152.95
> 
> Bind port          : 5443
> 
> KCP support        : true
> 
> vhost http port    : 8880
> 
> vhost https port   : 8443
> 
> Dashboard port     : 7500
> 
> token              : 123456
> 
> subdomain_host     : 112.11.152.95
> 
> tcp_mux            : true
> 
> Max Pool count     : 50
> 
> Log level          : info
> 
> Log max days       : 3
> 
> Log file           : enable
> 
> ================================================
> 
> frps Dashboard     : http://112.11.152.95:7500/
> 
> Dashboard user     : admin
> 
> Dashboard password : 123456
> 
> ================================================

Usage: /etc/init.d/frps {start|stop|restart|status|config|version}
