### ISSUE TITLE
关于tcp和SFTP设置的问题

### ISSUE THREAD

**Issue by zolopp** [mvscode/frps-onekey#48]
下午一直在配置这个程序，现在遇到的问题

问题1：ssh配置无法生效，服务端也看不到对应连接状态，ssh访问不能到目标设备，只能到frp服务器。

配置：本地和服务端口都是22，由于客户端选择tcp协议就无法设置二级域名，所以配置是指向主域名的。
![111](https://user-images.githubusercontent.com/58029653/127862433-9f49c1df-791a-49cc-911e-c07861341352.JPG)
问题2：选择sftp服务以后，不太懂这个配置，没有用户名和密码设置和密钥，不知道如何使用，这个问题比较菜
![1222](https://user-images.githubusercontent.com/58029653/127863728-b3c2a7bc-ea26-4cae-b65e-430fbfb75d64.JPG)

**Comment by zolopp** [comment]
port unavailable 查了客户端日志，端口是开放的，部知道什么问题

**Comment by MvsCode** [comment]
>  port unavailable 查了客户端日志，端口是开放的，部知道什么问题

你先看看服务端时候是否配置成功，是否可以登陆服务端的控制面板
