### ISSUE TITLE
正在加载服务器IP，请稍候。。。

### ISSUE THREAD

**Issue by NaDuoHu** [MvsCode/frps-onekey#50]
Please select frps download url:
[1].aliyun (default)
[2].github 
Enter your choice (1, 2 or exit. default [aliyun]): 
-----------------------------------
       Your select: aliyun    
-----------------------------------
Loading network version for frps, please wait...
frps Latest release file frp_0.37.1_linux_amd64.tar.gz
Loading You Server IP, please wait...

日志一直这样卡着不动有什么解决办法吗  阿里云 CentOS 8.2

**Comment by MvsCode** [comment]
已更新最新版本，请再次尝试
