### ISSUE TITLE
download frps ... failed  from github

### ISSUE THREAD

**Issue by ycycn** [MvsCode/frps-onekey#57]
Press any key to start...or Press Ctrl+c to cancel
frps install path:/usr/local/frps
config file for frps ... done
download frps ... failed

**Comment by PilotXia** [comment]
me too

**Comment by a2651011** [comment]
http://chmod/
Resolving chmod (chmod)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘chmod’
--2022-03-18 01:49:54--  http://700/
Resolving 700 (700)... 0.0.2.188
Connecting to 700 (700)|0.0.2.188|:80... ^C
连接失败，一直安装不了。

**Comment by qq635938204** [comment]
同样问题

**Comment by MvsCode** [comment]
> 同样问题

沒事啊，我下載很好啊

**Comment by gearfox** [comment]
就是无法下载

**Comment by xiajinchun** [comment]
Press any key to start...or Press Ctrl+c to cancel
frps install path:/usr/local/frps
config file for frps ... done
download frps ... failed
