### ISSUE TITLE
frps安装失败

### ISSUE THREAD

**Issue by ligang2020** [mvscode/frps-onekey#64]
[之前可以安装，现在Aliyun和Github安装，全部安装不了。失败，不知道问题出在哪里？
报错代码：
[opc@frp-hg02 ~]$ sudo su
[root@frp-hg02 opc]# wget https://raw.githubusercontent.com/MvsCode/frp-onekey/master/install-frps.sh -O ./install-frps.sh
--2022-07-27 21:58:46--  https://raw.githubusercontent.com/MvsCode/frp-onekey/master/install-frps.sh
正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：38102 (37K) [text/plain]
正在保存至: “./install-frps.sh”

100%[=====================================================================================================================================================================>] 38,102      --.-K/s 用时 0s      

2022-07-27 21:58:47 (77.6 MB/s) - 已保存 “./install-frps.sh” [38102/38102])

[root@frp-hg02 opc]# chmod 700 ./install-frps.sh
[root@frp-hg02 opc]# ./install-frps.sh install
bash: ./install-frps.sh: /bin/bash: 坏的解释器: 文本文件忙
[root@frp-hg02 opc]# 
[root@frp-hg02 opc]# 
[root@frp-hg02 opc]# 4#$

**Comment by MvsCode** [comment]
把vps重新安装一下吧
