### ISSUE TITLE
When executing the installer, it keeps showin: Check updates for shell...

### ISSUE THREAD

**Issue by yuluod** [mvscode/frps-onekey#69]
System is Debian11
Linux VM-12-11-debian 5.10.0-19-amd64

**Comment by MvsCode** [comment]
> System is Debian11
> 
> Linux VM-12-11-debian 5.10.0-19-amd64 
> 
> 

you should checking the Debian
System latest version

**Comment by gearfox** [comment]
偶尔就是会出现Check updates for shell卡住

**Comment by xyz0101** [comment]
centos7也卡在这里，不知道啥情况

**Comment by MvsCode** [comment]
> centos7也卡在这里，不知道啥情况

try again
