### ISSUE TITLE
kcp端口与tcp 端口重合时，无法使用kcp

### ISSUE THREAD

**Issue by mlch911** [MvsCode/frps-onekey#9]
kcp端口与tcp 端口重合时，无法使用kcp。
当两个端口分开时，使用正常。
客户端是0.20.0，服务端时0.27.0，不知道是不是客户端版本太低的缘故。

**Comment by MvsCode** [comment]
协议不同，端口不能重复，跟版本号关系不要大，建议使用不同端口，最好使用同一版本

**Comment by mlch911** [comment]
嗯嗯，配置文件里的注释写的是可以同一端口……
