### ISSUE TITLE
操作系统支持

### ISSUE THREAD

**Issue by FireSpell1** [mvscode/frps-onekey#90]
麻烦增加下RHEL8和9系列的支持

**Comment by MvsCode** [comment]
> 麻烦增加下RHEL8和9系列的支持

你是指這個腳本還是frp？

**Comment by FireSpell1** [comment]
太久了记不清了，应该是脚本

**Comment by MvsCode** [comment]
> 太久了记不清了，应该是脚本

本來就支持的呢，只是要對應架構的包，不挑系統

**Comment by mvscode** [comment]
> 麻烦增加下RHEL8和9系列的支持

#112 
已支持RHEL
