### ISSUE TITLE
0.52版本启用新的配置文件，希望尽快支持

### ISSUE THREAD

**Issue by xingtongsf** [MvsCode/frps-onekey#91]
0.52版本启用新的配置文件，不再引用frps.ini，而是使用frps.toml.配置项也做了些许更改。希望尽快支持更改引用。谢谢

**Comment by xiwangly2** [comment]
已做出部分修改：PR 待处理

仍有TODO

https://github.com/MvsCode/frps-onekey/pull/95

**Comment by MvsCode** [comment]
#108
