### ISSUE TITLE
不想改下支持其他CentOS的衍生品？

### ISSUE THREAD

**Issue by lendy98** [mvscode/frps-onekey#94]
比如：
AlmaLinux release 9.3 (Shamrock Pampas Cat)

**Comment by MvsCode** [comment]
> 比如：
> 
> AlmaLinux release 9.3 (Shamrock Pampas Cat)

這個是啥系統

**Comment by mvscode** [comment]
> 比如： AlmaLinux release 9.3 (Shamrock Pampas Cat)

#90 

> 比如： AlmaLinux release 9.3 (Shamrock Pampas Cat)

#90
