### ISSUE TITLE
启动失败start failed

### ISSUE THREAD

**Issue by chyl168** [MvsCode/frps-onekey#98]
root@ubuntu:~# frps start
+---------------------------------------------------------+
|     Manager for Frps, Author Clang, Maintainer MvsCode      |
+---------------------------------------------------------+
Starting Frps (0.58.1)...start failed

安装过程中好象有些文件或文件夹没有（done）

==============================================

Press any key to start...or Press Ctrl+c to cancel
frps install path:/usr/local/frps
config file for frps ... done
download frps ... done
download /etc/init.d/frps... done
setting frps boot... done
+---------------------------------------------------------+
|     Manager for Frps, Author Clang, Maintainer MvsCode      |
+---------------------------------------------------------+
Starting Frps (0.58.1)...start failed

+------------------------------------------------------------+
|   frps for Linux Server, Author Clang ，Mender MvsCode     |
|      A tool to auto-compile & install frps on Linux        |
+------------------------------------------------------------+

Congratulations, frps install completed!
================================================

**Comment by chyl168** [comment]
是启动失败卸载重装时的提示

**Comment by MvsCode** [comment]
> 是启动失败卸载重装时的提示

你是打算重裝？然後重裝時出現問題？

**Comment by chyl168** [comment]
是重装过程提示的信息，初装时没注意，但也启动不了

**Comment by MvsCode** [comment]
> 是重装过程提示的信息，初装时没注意，但也启动不了start failed

試試先卸載服務，然後清除乾淨文件夾，再從新安裝，懷疑重裝時候舊文件夾還在，新的的文件夾就變成有序號，比如.1 -1這種，導致後面安裝命令對不上

**Comment by chyl168** [comment]
清除了再装还是不行，启动不了，估计是0.58.1版本压缩包文件和以前不太一样的原因吧
Press any key to start...or Press Ctrl+c to cancel
frps install path:/usr/local/frps
config file for frps ... done
download frps ... done
download /etc/init.d/frps... done
setting frps boot... done
+---------------------------------------------------------+
|     Manager for Frps, Author Clang, Maintainer MvsCode      |
+---------------------------------------------------------+
Starting Frps (0.58.1)...start failed

+------------------------------------------------------------+
|   frps for Linux Server, Author Clang ï¼Mender MvsCode     |
|      A tool to auto-compile & install frps on Linux        |
+------------------------------------------------------------+


Congratulations, frps install completed!
。
。
frps status manage : frps {start|stop|restart|status|config|version}
Example:
  start: frps start
   stop: frps stop
restart: frps restart
root@ubuntu:~# frps start
+---------------------------------------------------------+
|     Manager for Frps, Author Clang, Maintainer MvsCode      |
+---------------------------------------------------------+
Starting Frps (0.58.1)...start failed
root@ubuntu:~# 




卸载后先删除了：
1、~目录（root目录）下所有带frps文件 frps-install.log frps.log frps-uninstall.log frps-update.log install-frps.sh install-frps.shchmod
2、/etc/init.d/下所有带frps文件 frps.log
/usr/local/下frps目录已不存在，卸载时自动删除了

**Comment by chyl168** [comment]
1、.INI文件格式可能是您改了，此次安装后变成.toml
root@ubuntu:/usr/local/frps# dir
frps  frps.log	frps.toml
2、不带路径执行 frps -c /usr/local/frps/frps.toml 变成VIM打开了.toml
3、带路径执行 /usr/local/frps/frps -c /usr/local/frps/frps.toml 可以，不过有端口占用警告
WARNING: ini format is deprecated and the support will be removed in the future, please use yaml/json/toml format instead!
create server listener error, listen tcp 0.0.0.0:443: bind: address already in use
root@ubuntu:/usr/local/frps# 
4、端口改成4443后运行start成功
root@ubuntu:/usr/local/frps# vi /usr/local/frps/frps.toml
root@ubuntu:/usr/local/frps# /usr/local/frps/frps -c /usr/local/frps/frps.toml
WARNING: ini format is deprecated and the support will be removed in the future, please use yaml/json/toml format instead!

exit
frps start
^C
root@ubuntu:/usr/local/frps# frps start
+---------------------------------------------------------+
|     Manager for Frps, Author Clang, Maintainer MvsCode      |
+---------------------------------------------------------+
Starting Frps (0.58.1)... done
Frps (pid ) is running.

**Comment by MvsCode** [comment]
> 1、.INI文件格式可能是您改了，此次安装后变成.toml
> 
> root@ubuntu:/usr/local/frps# dir
> 
> frps  frps.log	frps.toml
> 
> 2、不带路径执行 frps -c /usr/local/frps/frps.toml 变成VIM打开了.toml
> 
> 3、带路径执行 /usr/local/frps/frps -c /usr/local/frps/frps.toml 可以，不过有端口占用警告
> 
> WARNING: ini format is deprecated and the support will be removed in the future, please use yaml/json/toml format instead!
> 
> create server listener error, listen tcp 0.0.0.0:443: bind: address already in use
> 
> root@ubuntu:/usr/local/frps# 
> 
> 4、端口改成4443后运行start成功
> 
> root@ubuntu:/usr/local/frps# vi /usr/local/frps/frps.toml
> 
> root@ubuntu:/usr/local/frps# /usr/local/frps/frps -c /usr/local/frps/frps.toml
> 
> WARNING: ini format is deprecated and the support will be removed in the future, please use yaml/json/toml format instead!
> 
> 
> 
> exit
> 
> frps start
> 
> ^C
> 
> root@ubuntu:/usr/local/frps# frps start
> 
> +---------------------------------------------------------+
> 
> |     Manager for Frps, Author Clang, Maintainer MvsCode      |
> 
> +---------------------------------------------------------+
> 
> Starting Frps (0.58.1)... done
> 
> Frps (pid ) is running.
> 
> 5、HTTP面板打开成功
> 
> 

改成toml就可以了？

**Comment by chyl168** [comment]
不是，要带路径手动运行/usr/local/frps/frps -c /usr/local/frps/frps.toml

**Comment by MvsCode** [comment]
> 不是，要带路径手动运行/usr/local/frps/frps -c /usr/local/frps/frps.toml
> 
> 

控制面板可以打開嗎

**Comment by chyl168** [comment]
运行后下面这个面板可以打开。。不过后来客户端安装失败，还在排查中
![image](https://github.com/MvsCode/frps-onekey/assets/76003950/f688b0e6-50af-4363-80ce-16e994a001b4)
