### ISSUE TITLE
今天一直无法安装，提示download frps  failed

### ISSUE THREAD

**Issue by wfniub** [MvsCode/frps-onekey#99]
Press any key to start...or Press Ctrl+c to cancel
frps install path:/usr/local/frps
config file for frps ... done
download frps ... failed

![image](https://github.com/MvsCode/frps-onekey/assets/59757806/996e3fe8-e6b0-4e00-b87c-ed572d8a9bf2)

**Comment by wfniub** [comment]
![image](https://github.com/MvsCode/frps-onekey/assets/59757806/92d1a251-3920-43dc-884c-a26819f0e464)
检测不到版本！

**Comment by MvsCode** [comment]
> ![image](https://github.com/MvsCode/frps-onekey/assets/59757806/92d1a251-3920-43dc-884c-a26819f0e464)
> 
> 检测不到版本！

再試一下，更新了一下

**Comment by znwhyo** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/59757806/336782688-92d1a251-3920-43dc-884c-a26819f0e464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDAzNjcsIm5iZiI6MTcxNzY0MDA2NywicGF0aCI6Ii81OTc1NzgwNi8zMzY3ODI2ODgtOTJkMWEyNTEtMzkyMC00M2RjLTg4NGMtYTI2ODE5ZjBlNDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAyMTQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NGEyNzQ4OTMxMDg5YWU3M2U2YTMwZGFjNjAwZjhiNTY2YmI0N2U1ODU2YmVlYTkyNTdhNmQ2MzI2ZGEyZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UW5IuDSMjZJ6NMz4MxbHET6I5uGM7IozJ5Ew1gANZtQ)
> > 检测不到版本！
> 
> 再试一下，更新一下

<img width="538" alt="image" src="https://github.com/MvsCode/frps-onekey/assets/101561860/3b03b909-1567-4400-a8fc-6067836b2543">
还是不行

**Comment by MvsCode** [comment]
> > > ![图像](https://private-user-images.githubusercontent.com/59757806/336782688-92d1a251-3920-43dc-884c-a26819f0e464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDAzNjcsIm5iZiI6MTcxNzY0MDA2NywicGF0aCI6Ii81OTc1NzgwNi8zMzY3ODI2ODgtOTJkMWEyNTEtMzkyMC00M2RjLTg4NGMtYTI2ODE5ZjBlNDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAyMTQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NGEyNzQ4OTMxMDg5YWU3M2U2YTMwZGFjNjAwZjhiNTY2YmI0N2U1ODU2YmVlYTkyNTdhNmQ2MzI2ZGEyZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UW5IuDSMjZJ6NMz4MxbHET6I5uGM7IozJ5Ew1gANZtQ)
> 
> > > 检测不到版本！
> 
> > 
> 
> > 再试一下，更新一下
> 
> 
> 
> <img width="538" alt="image" src="https://github.com/MvsCode/frps-onekey/assets/101561860/3b03b909-1567-4400-a8fc-6067836b2543">
> 
> 还是不行

![image](https://github.com/MvsCode/frps-onekey/assets/37238560/420a7376-82a4-499f-9346-a6a368e5da53)

国内的vps？

**Comment by znwhyo** [comment]
> > > > ![图像](https://private-user-images.githubusercontent.com/59757806/336782688-92d1a251-3920-43dc-884c-a26819f0e464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDAzNjcsIm5iZiI6MTcxNzY0MDA2NywicGF0aCI6Ii81OTc1NzgwNi8zMzY3ODI2ODgtOTJkMWEyNTEtMzkyMC00M2RjLTg4NGMtYTI2ODE5ZjBlNDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAyMTQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NGEyNzQ4OTMxMDg5YWU3M2U2YTMwZGFjNjAwZjhiNTY2YmI0N2U1ODU2YmVlYTkyNTdhNmQ2MzI2ZGEyZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UW5IuDSMjZJ6NMz4MxbHET6I5uGM7IozJ5Ew1gANZtQ)
> > 
> > 
> > > > 检测不到版本！
> > 
> > 
> > > 
> > 
> > 
> > > 再试一下，更新一下
> > 
> > 
> > <img alt="图像" width="538" src="https://private-user-images.githubusercontent.com/101561860/337077438-3b03b909-1567-4400-a8fc-6067836b2543.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTIxNzQsIm5iZiI6MTcxNzY1MTg3NCwicGF0aCI6Ii8xMDE1NjE4NjAvMzM3MDc3NDM4LTNiMDNiOTA5LTE1NjctNDQwMC1hOGZjLTYwNjc4MzZiMjU0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNTMxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWFkZmZhNGMxYTVjZWUzNWFkYTk3NzUxZDlmMDdjN2ZiOWJkOTM3ZGU4NmE0YTc1NTg4ODg1ODAzN2IwMDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2BqsmKYTyjfWKRz1eS0Rj5qQqLdOXoMFdHPQC2HBV6k">
> > 还是不行
> 
> ![图像](https://private-user-images.githubusercontent.com/37238560/337094836-420a7376-82a4-499f-9346-a6a368e5da53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTIxNzQsIm5iZiI6MTcxNzY1MTg3NCwicGF0aCI6Ii8zNzIzODU2MC8zMzcwOTQ4MzYtNDIwYTczNzYtODJhNC00OTlmLTkzNDYtYTZhMzY4ZTVkYTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA1MzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OWY1ZTg5ODg4MzI1MzRhNDJjYjNhNTBiOWQ0YWY0ODRmNTk0OGM3MWI1NWNjZGEzM2FlYWQ2MGFjMWIwZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yjdAXKOQFeRcyDh38ngekwovwcPqfGt3oXEvK7V1-ko)
> 
> 国内的vps？

是的 国内的不能用吗？

**Comment by MvsCode** [comment]
> > > > > ![图像](https://private-user-images.githubusercontent.com/59757806/336782688-92d1a251-3920-43dc-884c-a26819f0e464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDAzNjcsIm5iZiI6MTcxNzY0MDA2NywicGF0aCI6Ii81OTc1NzgwNi8zMzY3ODI2ODgtOTJkMWEyNTEtMzkyMC00M2RjLTg4NGMtYTI2ODE5ZjBlNDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAyMTQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NGEyNzQ4OTMxMDg5YWU3M2U2YTMwZGFjNjAwZjhiNTY2YmI0N2U1ODU2YmVlYTkyNTdhNmQ2MzI2ZGEyZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UW5IuDSMjZJ6NMz4MxbHET6I5uGM7IozJ5Ew1gANZtQ)
> 
> > > 
> 
> > > 
> 
> > > > > 检测不到版本！
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 再试一下，更新一下
> 
> > > 
> 
> > > 
> 
> > > <img alt="图像" width="538" src="https://private-user-images.githubusercontent.com/101561860/337077438-3b03b909-1567-4400-a8fc-6067836b2543.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTIxNzQsIm5iZiI6MTcxNzY1MTg3NCwicGF0aCI6Ii8xMDE1NjE4NjAvMzM3MDc3NDM4LTNiMDNiOTA5LTE1NjctNDQwMC1hOGZjLTYwNjc4MzZiMjU0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNTMxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWFkZmZhNGMxYTVjZWUzNWFkYTk3NzUxZDlmMDdjN2ZiOWJkOTM3ZGU4NmE0YTc1NTg4ODg1ODAzN2IwMDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2BqsmKYTyjfWKRz1eS0Rj5qQqLdOXoMFdHPQC2HBV6k">
> 
> > > 还是不行
> 
> > 
> 
> > ![图像](https://private-user-images.githubusercontent.com/37238560/337094836-420a7376-82a4-499f-9346-a6a368e5da53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTIxNzQsIm5iZiI6MTcxNzY1MTg3NCwicGF0aCI6Ii8zNzIzODU2MC8zMzcwOTQ4MzYtNDIwYTczNzYtODJhNC00OTlmLTkzNDYtYTZhMzY4ZTVkYTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA1MzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OWY1ZTg5ODg4MzI1MzRhNDJjYjNhNTBiOWQ0YWY0ODRmNTk0OGM3MWI1NWNjZGEzM2FlYWQ2MGFjMWIwZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yjdAXKOQFeRcyDh38ngekwovwcPqfGt3oXEvK7V1-ko)
> 
> > 
> 
> > 国内的vps？
> 
> 
> 
> 是的 国内的不能用吗？

你试试用gitee

**Comment by znwhyo** [comment]
> > > > > > ![图像](https://private-user-images.githubusercontent.com/59757806/336782688-92d1a251-3920-43dc-884c-a26819f0e464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDAzNjcsIm5iZiI6MTcxNzY0MDA2NywicGF0aCI6Ii81OTc1NzgwNi8zMzY3ODI2ODgtOTJkMWEyNTEtMzkyMC00M2RjLTg4NGMtYTI2ODE5ZjBlNDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAyMTQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NGEyNzQ4OTMxMDg5YWU3M2U2YTMwZGFjNjAwZjhiNTY2YmI0N2U1ODU2YmVlYTkyNTdhNmQ2MzI2ZGEyZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UW5IuDSMjZJ6NMz4MxbHET6I5uGM7IozJ5Ew1gANZtQ)
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > 检测不到版本！
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 再试一下，更新一下
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > <img alt="图像" width="538" src="https://private-user-images.githubusercontent.com/101561860/337077438-3b03b909-1567-4400-a8fc-6067836b2543.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTIxNzQsIm5iZiI6MTcxNzY1MTg3NCwicGF0aCI6Ii8xMDE1NjE4NjAvMzM3MDc3NDM4LTNiMDNiOTA5LTE1NjctNDQwMC1hOGZjLTYwNjc4MzZiMjU0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNTMxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWFkZmZhNGMxYTVjZWUzNWFkYTk3NzUxZDlmMDdjN2ZiOWJkOTM3ZGU4NmE0YTc1NTg4ODg1ODAzN2IwMDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2BqsmKYTyjfWKRz1eS0Rj5qQqLdOXoMFdHPQC2HBV6k">
> > 
> > 
> > > > 还是不行
> > 
> > 
> > > 
> > 
> > 
> > > ![图像](https://private-user-images.githubusercontent.com/37238560/337094836-420a7376-82a4-499f-9346-a6a368e5da53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTIxNzQsIm5iZiI6MTcxNzY1MTg3NCwicGF0aCI6Ii8zNzIzODU2MC8zMzcwOTQ4MzYtNDIwYTczNzYtODJhNC00OTlmLTkzNDYtYTZhMzY4ZTVkYTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA1MzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OWY1ZTg5ODg4MzI1MzRhNDJjYjNhNTBiOWQ0YWY0ODRmNTk0OGM3MWI1NWNjZGEzM2FlYWQ2MGFjMWIwZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yjdAXKOQFeRcyDh38ngekwovwcPqfGt3oXEvK7V1-ko)
> > 
> > 
> > > 
> > 
> > 
> > > 国内的vps？
> > 
> > 
> > 是的 国内的不能用吗？
> 
> 你试试用gitee

第一步选gitee吗 也是这样的failed

**Comment by MvsCode** [comment]
> > > > > > > ![图像](https://private-user-images.githubusercontent.com/59757806/336782688-92d1a251-3920-43dc-884c-a26819f0e464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDAzNjcsIm5iZiI6MTcxNzY0MDA2NywicGF0aCI6Ii81OTc1NzgwNi8zMzY3ODI2ODgtOTJkMWEyNTEtMzkyMC00M2RjLTg4NGMtYTI2ODE5ZjBlNDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAyMTQyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NGEyNzQ4OTMxMDg5YWU3M2U2YTMwZGFjNjAwZjhiNTY2YmI0N2U1ODU2YmVlYTkyNTdhNmQ2MzI2ZGEyZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UW5IuDSMjZJ6NMz4MxbHET6I5uGM7IozJ5Ew1gANZtQ)
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > 检测不到版本！
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > 再试一下，更新一下
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > <img alt="图像" width="538" src="https://private-user-images.githubusercontent.com/101561860/337077438-3b03b909-1567-4400-a8fc-6067836b2543.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTIxNzQsIm5iZiI6MTcxNzY1MTg3NCwicGF0aCI6Ii8xMDE1NjE4NjAvMzM3MDc3NDM4LTNiMDNiOTA5LTE1NjctNDQwMC1hOGZjLTYwNjc4MzZiMjU0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQwNTMxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWFkZmZhNGMxYTVjZWUzNWFkYTk3NzUxZDlmMDdjN2ZiOWJkOTM3ZGU4NmE0YTc1NTg4ODg1ODAzN2IwMDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2BqsmKYTyjfWKRz1eS0Rj5qQqLdOXoMFdHPQC2HBV6k">
> 
> > > 
> 
> > > 
> 
> > > > > 还是不行
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > ![图像](https://private-user-images.githubusercontent.com/37238560/337094836-420a7376-82a4-499f-9346-a6a368e5da53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTIxNzQsIm5iZiI6MTcxNzY1MTg3NCwicGF0aCI6Ii8zNzIzODU2MC8zMzcwOTQ4MzYtNDIwYTczNzYtODJhNC00OTlmLTkzNDYtYTZhMzY4ZTVkYTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA1MzExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OWY1ZTg5ODg4MzI1MzRhNDJjYjNhNTBiOWQ0YWY0ODRmNTk0OGM3MWI1NWNjZGEzM2FlYWQ2MGFjMWIwZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yjdAXKOQFeRcyDh38ngekwovwcPqfGt3oXEvK7V1-ko)
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > 国内的vps？
> 
> > > 
> 
> > > 
> 
> > > 是的 国内的不能用吗？
> 
> > 
> 
> > 你试试用gitee
> 
> 
> 
> 第一步选gitee吗 也是这样的failed

试试现在wget gitee

**Comment by xinzhongyouhai** [comment]
同样问题~~~Press any key to start...or Press Ctrl+c to cancel
frps install path:/usr/local/frps
config file for frps ... done
download frps ... failed
root@ubun2004:~#

**Comment by MvsCode** [comment]
Done
